### ISSUE TITLE
Running a game in macos doesn't show anything

### ISSUE THREAD

**Issue by javierfernandes** [ProyectoFinal2015/wollok-game#11]
If you run a wollok game in OS X Yosemite 10.10.3 the process just stays there executing but nothing happens.
It won't show any error in the console, neither will open a new window.

**Comment by javierfernandes** [comment]
If I set this variables I can at least see something in the console

```
System.setProperty("org.lwjgl.util.Debug", "true");
```

Here's the output

```
[LWJGL] getPathFromClassLoader: searching for: openal
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.net.URLClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.security.SecureClassLoader.findLibrary(java.lang.String)
[LWJGL] getPathFromClassLoader: searching for: lwjgl
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.net.URLClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.security.SecureClassLoader.findLibrary(java.lang.String)
[LWJGL] Found 10 OpenAL paths
[LWJGL] Testing '/var/folders/rl/wdf7p8d578g_4rdl91fy993r0000gp/T/libgdxjfernandes/f7649394/openal.dylib'
[LWJGL] Found OpenAL at '/var/folders/rl/wdf7p8d578g_4rdl91fy993r0000gp/T/libgdxjfernandes/f7649394/openal.dylib'
[LWJGL] MemoryUtil Accessor: AccessorUnsafe
[LWJGL] Initial mode: 1680 x 1050 x 32 @0Hz
```

**Comment by javierfernandes** [comment]
Tried jdk 8 an jdk7, same result

**Comment by javierfernandes** [comment]
Ok, resolved (partially).

I just remembered that this happened to me before.
In eclipse you need to uncheck and option from the launcher config, related to SWT. Otherwise it won't work (-XstartOnFirstThread)
I'm pretty sure this is an issue using libgdx along with SWT in OS X.

<img width="529" alt="screen shot 2015-09-22 at 10 51 29" src="https://cloud.githubusercontent.com/assets/4428120/10020214/1131397e-6118-11e5-8657-eb6ae700630a.png">

I'll try to see how wollok can launch the game to avoid this

**Comment by charlyraffellini** [comment]
Thanks @javierfernandes for advices. You are the first who tried our implementation in OS X.

:raised_hands:

**Comment by javierfernandes** [comment]
Fixed in   https://github.com/uqbar-project/wollok/issues/248

https://github.com/uqbar-project/wollok/commit/9440dc4bf12c9c8841b72a365bc08b1ffe723dd5

You just need to merge
